### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by codeliner** [RayRutjes/domain#13]
Hey Ray,

you've requested some feedback for your repo on the DDDinPHP mailing list. Here it is :-)
Good job so fare :+1: I like the naming convention and the structure.

I only have some hints and a few notes to may start a discussion:
1. I would move the method `AggregateRoot::id` (or remove it, see point two) to the `Entity` interface and remove the AggregateRoot interface. The methods `AggregateRoot::recordEvent` and `AggregateRoot::pullRecordedEvents` should not be public. `Only the AggregateRoot decides when it records an event!` And as long as you don't implement EventSourcing you don't need the pullRecordedEvents method. Simply return a DomainEvent from the AggregateRoot method which handles the action. If you implement EventSourcing later the pullRecordedEvents method should not be public anyway. Pulling the events from the AR would then be the job of an `Unit of Work` which is normally located in the infrastructure and can use reflection or a decorator to access pending events. Such infrastructure concerns should not pollute the public API of your ARs.
2. The `AggregateRoot::id` method is generic. In DDD you want to have explicit identifiers like a UserId, TrackingId, etc. Sure in most cases these VOs will extend the Identifier class but you will end up having two public methods like Cargo::id and Cargo::TrackingId. Question is: `Why do you need the method?` Your current Entity interface looks good as it is: Entities are compared by identity. That is the important information. No need for a public id method.
3. Your current event publisher implementation allows only one event per subscriber. You will run into trouble with this when you need to implement a ProcessManager. Normally a PM needs to subscribe to multiple domain events to coordinate follow up tasks and/or `track state of a long running process`. Also the publisher requires registration of instantiated subscribers. Sooner or later you will need to implement a lazy loading mechanism but that is a different story.
4. Do you really need to support PHP 5.4? If not you could require PHP 5.5 and use \DateTimeImmutable instead of \DateTime. Then you don't need to clone it before returning it from an event.

That's it. Hope it is useful.

**Comment by rayrutjes** [comment]
Thank you for your feedback @codeliner , your different points totally make sense. I have been quite overwhelmed lately with DDD, CQRS, ES, I wanted this project to cover only the DDD aspect.
After a few more days of accumulating ES knowledge, I think this library will be more focused on ES after all.

I came to the conclusion that ES is a really nice way to have a domain that really reflects the domain model, by capturing the intent of the user and reflecting it correctly into the design in the form of events.

Your first two points make sense, and as Greg Young says, public getters/setters should be a code smell.

Concerning the event publisher, it is gonna be reviewed to fit into ES nicely.

For the last point, I am aware of the DateTimeImmutable. I might drop support for 5.3 and then use it which would be nice.

**Comment by rayrutjes** [comment]
This package can now be considered highly deprecated as I have been focusing on building a new one focused on implementing EventSourcing at the heart of the library.

Please visit https://github.com/RayRutjes/domain-foundation and feel free to give me some feedback.
