### ISSUE TITLE
Demo / Example

### ISSUE THREAD

**Issue by illuminate3** [RayRutjes/domain#8]
Do you have a simple example of how you are implementing this?

Thanks!

**Comment by rayrutjes** [comment]
I definitely will include an example folder with some concrete implementations.

**Comment by illuminate3** [comment]
Thanks!

Not looking for a full demo app but just something that would be a start point. I've always wanted to get into DDD but understanding and implementing the concepts are different.

I figure that this would be great for a cart/store but what do you think for a CMS (pages)?

**Comment by rayrutjes** [comment]
DDD is very efficient for complex projects. It aims to make the implicit, explicit, by designing a model that is closest possible from how it is defined by the domain experts of your project.
DDD is not suited for any project, even though, the main principles and guidelines it provides can still be applied in any project. I will list a bunch of reading at the end of the Readme for those who wanna dig in further.

**Comment by illuminate3** [comment]
Thanks!

**Comment by rayrutjes** [comment]
This package can now be considered highly deprecated as I have been focusing on building a new one focused on implementing EventSourcing at the heart of the library.

Please visit https://github.com/RayRutjes/domain-foundation and feel free to give me some feedback.

I am actually working on a whole example repository to illustrate the different mechanisms.
